'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports DevExpress.Xpo
Imports DevExpress.ExpressApp
Imports DevExpress.Persistent.Base
Imports DevExpress.Persistent.BaseImpl
<DefaultClassOptions> _
Public Partial Class Character
  Inherits DevExpress.Persistent.BaseImpl.BaseObject
  Private _age As System.Int32
  Private _weight As System.Double
  Private _height As System.Double
  Private _eyeColor As System.String
  Private _hairColor As System.String
  Private _gender As PathfinderModule.Gender
  Private _size As PathfinderModule.Size
  Private _deity As System.String
  Private _alignment As PathfinderModule.Alignment
  Private _name As System.String
  Public Sub New(ByVal session As Session)
    MyBase.New(session)
  End Sub
  Public Property Name As System.String
    Get
      Return _name
    End Get
    Set
      SetPropertyValue("Name", _name, value)
    End Set
  End Property
  Public Property Alignment As PathfinderModule.Alignment
    Get
      Return _alignment
    End Get
    Set
      SetPropertyValue("Alignment", _alignment, value)
    End Set
  End Property
  Public Property Deity As System.String
    Get
      Return _deity
    End Get
    Set
      SetPropertyValue("Deity", _deity, value)
    End Set
  End Property
  Public Property Size As PathfinderModule.Size
    Get
      Return _size
    End Get
    Set
      SetPropertyValue("Size", _size, value)
    End Set
  End Property
  Public Property Gender As PathfinderModule.Gender
    Get
      Return _gender
    End Get
    Set
      SetPropertyValue("Gender", _gender, value)
    End Set
  End Property
  Public Property Age As System.Int32
    Get
      Return _age
    End Get
    Set
      SetPropertyValue("Age", _age, value)
    End Set
  End Property
  Public Property Weight As System.Double
    Get
      Return _weight
    End Get
    Set
      SetPropertyValue("Weight", _weight, value)
    End Set
  End Property
  Public Property Height As System.Double
    Get
      Return _height
    End Get
    Set
      SetPropertyValue("Height", _height, value)
    End Set
  End Property
  Public Property HairColor As System.String
    Get
      Return _hairColor
    End Get
    Set
      SetPropertyValue("HairColor", _hairColor, value)
    End Set
  End Property
  Public Property EyeColor As System.String
    Get
      Return _eyeColor
    End Get
    Set
      SetPropertyValue("EyeColor", _eyeColor, value)
    End Set
  End Property
End Class
