'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports DevExpress.Xpo
Imports DevExpress.ExpressApp
Imports DevExpress.Persistent.Base
Imports DevExpress.Persistent.BaseImpl
<DefaultClassOptions> _
Public Partial Class Race
  Inherits DevExpress.Persistent.BaseImpl.BaseObject
  Private _character As PathfinderModule.Character
  Public Sub New(ByVal session As Session)
    MyBase.New(session)
  End Sub
  Public Property Character As PathfinderModule.Character
    Get
      Return _character
    End Get
    Set
      If _character Is value Then
        Return
      End If
      Dim prevCharacter As PathfinderModule.Character = _character
      _character = value
      If IsLoading Then
        Return
      End If
      If prevCharacter IsNot Nothing AndAlso prevCharacter.Race Is Me Then
        prevCharacter.Race = Nothing
      End If
      If _character IsNot Nothing Then
        _character.Race = Me
      End If
      OnChanged("Character")
    End Set
  End Property
End Class
